// <auto-generated />
namespace CFenix_Dev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AgregoRelacionDetalleVentaconTrabajo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AgregoRelacionDetalleVentaconTrabajo));
        
        string IMigrationMetadata.Id
        {
            get { return "201412031833455_Agrego Relacion Detalle Venta con Trabajo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
